version: '3.7'

services:

  web:
    build:
      context: Furs2Feathers
      dockerfile: api.Dockerfile
    image: jhbui1/f2f-api:1.0
  data:
    build:
      context: Furs2Feathers
      dockerfile: db.Dockerfile
    image: jhbui1/f2f-db:1.0