version: '3.7'

services:

  web:
    build:
      context: NotesService
      dockerfile: api.Dockerfile
    image: jhbui1/f2f-api:1.0

  data:
    build:
      context: NotesService
      dockerfile: db.Dockerfile
    image: nicholasescalona/f2f-db:1.0